name: PEYTONHOME DESIGN SOURCE
favicon: null
layout_spectrum: 0.4864884205162525
typography_spectrum: 0.75996
title: '& THE MARYLAND DESIGN CENTER'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#afb0ab'
    - '#5a1f35'
    - '#537700'
    - '#965038'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
